### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by aschrijver** [OpenHospitalityNetwork/openHospitality.network#17]
This repo needs a licens, both for the site code and for the content, or it'll be proprietary.

In my [Fedi Foundation](https://codeberg.org/fediverse/fedi-foundation) site I use `AGPL` for code and `CC0` for content. (This site facilitates that guest authors override the license and choose either `CC BY-SA` or `CC BY-NC-SA` for their own articles).

**Comment by mariha** [comment]
Thanks for pointing this out! As long as [fedi-trustroots](https://github.com/FediHospEx/federated-trustroots) codebase is licensed with MIT, this does not leave us much choice but to go with MIT, as per my understanding. Otherwise, if we for example chose AGPL for this repo and tracked issues here, we won't be allowed to transfer them to that codebase later on or even mention them in the patches.

So I'd say MIT [as for now](https://trello.com/c/BlOQsctV), until we decide with fedi-trustroots license. 
This should also allow us to change the license later on to more copy-left.

**Do we need separate license for the content?**

after: https://choosealicense.com/non-software/
> Open source software licenses can be also used for non-software works and are often the best choice, especially when the works in question can be edited and versioned as source
>
> **Documentation**
> Any open source software license or open license for media (see above) also applies to software documentation. If you use different licenses for your software and its documentation, be sure to specify that source code examples in the documentation are also licensed under the software license.

So I'd say no.

**Comment by aschrijver** [comment]
Why should the Jekyll website have the same license as the TR code in another repo?

> Do we need separate license for the content?

AFAIK the AGPL is good for code, but not so appropriate for published web content. Just like vice versa e.g. a CC BY license is not a good choice to publish code (CC0 I think is the only exception to that). But that is off the top of my head, so don't pin me to it :)

**Comment by mariha** [comment]
> Why should the Jekyll website have the same license as the TR code in another repo?

Because this website is a documentation for that code and this repo serves as an issues tracker for the other repo, should we decide to take different approach to federation (not based on TR but go-fed for example instead, or a suite of libraries that implement the protocol others can embed in their projects). 

I also find it simpler to have one license instead of two.

**Comment by mariha** [comment]
Merged MIT, we may change it when we change fedi-trustroots license https://github.com/OpenHospitalityNetwork/fedi-trustroots/issues/18
